//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackothon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class yzmYeniEntities : DbContext
    {
        public yzmYeniEntities()
            : base("name=yzmYeniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdresDetay> tblAdresDetay { get; set; }
        public virtual DbSet<tblKategori> tblKategori { get; set; }
        public virtual DbSet<tblKullanicilar> tblKullanicilar { get; set; }
        public virtual DbSet<tblMesajlar> tblMesajlar { get; set; }
        public virtual DbSet<tblSiparis> tblSiparis { get; set; }
        public virtual DbSet<tblSiparisDurum> tblSiparisDurum { get; set; }
        public virtual DbSet<tblUrunler> tblUrunler { get; set; }
    }
}
