//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackothon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdresDetay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAdresDetay()
        {
            this.tblKullanicilar = new HashSet<tblKullanicilar>();
        }
    
        public int kullaniciAdresID { get; set; }
        public string kullaniciAdres { get; set; }
        public string mahalle { get; set; }
        public int postaKod { get; set; }
        public string sehir { get; set; }
        public string ilce { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKullanicilar> tblKullanicilar { get; set; }
    }
}
