//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackothon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKullanicilar()
        {
            this.tblMesajlar = new HashSet<tblMesajlar>();
            this.tblMesajlar1 = new HashSet<tblMesajlar>();
        }
    
        public int kullaniciID { get; set; }
        public string kullaniciAdi { get; set; }
        public Nullable<int> kullaniciAdresID { get; set; }
        public string kullaniciSifre { get; set; }
        public string kullaniciEposta { get; set; }
    
        public virtual tblAdresDetay tblAdresDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMesajlar> tblMesajlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMesajlar> tblMesajlar1 { get; set; }
    }
}
