//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackothon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMesajlar
    {
        public int mesasjID { get; set; }
        public Nullable<int> gonderenID { get; set; }
        public Nullable<int> aliciID { get; set; }
        public string mesajIcerik { get; set; }
        public Nullable<int> urunID { get; set; }
        public Nullable<bool> okunduBilgisi { get; set; }
    
        public virtual tblKullanicilar tblKullanicilar { get; set; }
        public virtual tblKullanicilar tblKullanicilar1 { get; set; }
        public virtual tblUrunler tblUrunler { get; set; }
    }
}
